### ISSUE TITLE
Rbenv/Ruby 2.0.0-rc2 not showing as installed.

### ISSUE THREAD

**Issue by lushone** [marknotfound/rails-vagrant#1]
If I launch the Rails server and view the details about the Rails environment it says it's Ruby version 2.0.0 (i686-linux) & Rails version 4.0.0. But when I `vagrant ssh` into the VM and run `ruby -v` it shows it as Ruby 1.8 and Rails is not installed. Vim, Nodejs etc installed fine. I can see the rbenv files installed fine. When I `echo $PATH` it doesn't show the .rbenv directory in the path even though it's in the .profile file.

If this the intended procedure, then forgive me.

**Comment by lushone** [comment]
Ok so figured it out:

Once you `vagrant ssh` into the box `sudo su` then `source ~/.profile` and voila, rbenv is loaded into the path and the correct Ruby & Rails versions show up.

Would it be a better idea to have rbenv installed as the vagrant user rather than root?

**Comment by marknotfound** [comment]
Yes that would probably be better. I have a habit of logging in to all of my vagrant boxes as root so I never would have caught this.  I'll update it when I get a chance.  If you've already made a fix for it, feel free to submit a pull request and I will merge it in.  I'll leave this issue open until it's taken care of.

Thank you!

**Comment by lushone** [comment]
Out of curiosity, do you have a special config file that logs into `vagrant ssh` as root and cd's in to the default Rails app directory?

**Comment by marknotfound** [comment]
I don't.  I haven't actually even used this box yet short of just building it.  In my other dev boxes I just `vagrant ssh`, `sudo su`, and leave the terminal tab open while I'm working.
